### ISSUE TITLE
Line numbers showing 0

### ISSUE THREAD

**Issue by Ag0s** [adeptex/whispers#60]
**Describe the bug**
With the latest version of Whispers some results are reported with line number 0. When the finding is a complete file, I can understand this. But the output clearly shows secrets which are not on line 0.

**To Reproduce**
1. Using input 'whispers ./project/'
2. Run like usual

**Expected behavior**
I would suspect that whispers would show the correct line number the issue was found on.

**Screenshots**
Output:
```─$ whispers  ./      
[WARNING] [src/main/resources/application.properties:0] jwt_signingKey = Cs5TDZjPbhacFj*******************Nf6xk=
[WARNING] [src/main/resources/application.properties:0] service_user_details_api_key = fdd2**********************4274f
[WARNING] [backend/deserialization-userservice/server.py:6] API_KEY = fdd2**********************4274f
```
File content with line numbers:
```
1. management.endpoints.web.exposure.include=*
2. logging.file.name=./logs/log-file.log
3. # oops! :D
4. jwt.signingKey=Cs5TDZjPbhacFj*******************Nf6xk=
5. server.error.include-message=always
6. server.error.include-stacktrace=always
7. server.error.include-exception=true
8. server.port=8090
9. spring.profiles.default=standalone
10. 
11. service.user_details.url=http://localhost:9002
12. service.user_details.api_key=fdd2**********************4274f
```

**System information:**
 - OS (name, version): Ubuntu 18.04
 - Python version: 3.10.7
 - Whispers version: 2.1.3 & 2.1.4

**Comment by adeptex** [comment]
hey @Ag0s, thanks for reporting! will have a look..

**Comment by adeptex** [comment]
hey @Ag0s, i've pushed a patch for this bug. Releasing 2.1.5 now.

again, thanks very much for your report! please open another issue if the problem is not completely solved.

cheers!
