### ISSUE TITLE
Import json to defectDojo

### ISSUE THREAD

**Issue by rafaelsilvaa10builders** [adeptex/whispers#67]
Hello, 

I saw that now whispers is compatible with defectDojo.

I'm trying to import a report to it and I'm getting an error.

I took the example [unitTest](https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/master/unittests/scans/whispers/whispers_many_vul.json) report:

`[{"key": "01_static_password", "value": "hardcoded0", "file": "src/config.yml", "line": 12, "rule_id": "password", "message": "Password ", "severity": "CRITICAL"}, {"key": "02_static_passwords", "value": "Hardcoded1", "file": "src/config.yml", "line": 14, "rule_id": "password", "message": "Password", "severity": "CRITICAL"}, {"key": "02_static_passwords", "value": "hardCoded2", "file": "src/config.yml", "line": 15, "rule_id": "password", "message": "Password", "severity": "CRITICAL"}, {"key": "02_static_passwords", "value": "haRdcOded3", "file ": "src/config.yml", "line": 16, "rule_id": "password", "message": "Password", "severity": "CRITICAL"}, {"key": "password", "value": "hardcodEd", "file": "src/config.yml", "line": 19, "rule_id": "password", "message": "Password", "severity": "CRITICAL"} ].
`
The error I get is:
```
ERROR [dojo.engagement.views:683] Tried to update field dojo.Finding.references with a model instance, <Endpoint: https://cwe.mitre.org/data/definitions/798.html>. Use a value compatible with TextField.
Traceback (most recent call last):
```

Need to do something additional to resolve it?

Issue in DefectDojo Repo https://github.com/DefectDojo/django-DefectDojo/issues/7097

**Comment by adeptex** [comment]
hey @rafaelsilvaa10builders, thanks for your report. However, it does not contain sufficient details for debugging the issue. It's not clear at all how you are importing, what versions of whispers and dojo you are running, etc..

Please resubmit following the [provided template](https://github.com/adeptex/whispers/issues/new?assignees=&labels=&template=bug_report.md&title=) for logging bug reports.

Regards
