### ISSUE TITLE
Whispers command do not see the AWS Account ID in a .cs file

### ISSUE THREAD

**Issue by mericozkayagan** [adeptex/whispers#92]
**Describe the bug**
I want to use whispers in my dotnet projects in order to find any hardcoded secret. But in .cs files it seems it cannot look into them.

**To Reproduce**
Have a rule triggering secret within a json and a .cs file then run the  `whispers . -o scan_output.json` command. It will only show the json one.

**Expected behavior**
I want to find a hardcoded secret in every file in my project

**Screenshots**

**System information:**
 - OS (name, version):
 macOS Monterey 12.6.1
 - Python version: 
 python 3.11
 - Whispers version: 
 2.1.5

**Additional context**

**Comment by adeptex** [comment]
Hey @mericozkayagan, `.cs` files are C# source code, not structured text, so it's not supported by design.

Have a look at https://semgrep.dev for working with C# source.

Cheers
